apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: netmaker-k8s-ops-system
  labels:
    app.kubernetes.io/name: netmaker-k8s-ops
    app.kubernetes.io/instance: netmaker-k8s-ops
    app.kubernetes.io/component: webhook
spec:
  ports:
  - port: 443
    targetPort: 9443
    name: webhook
  selector:
    control-plane: controller-manager
