# permissions for end users to edit netmakerops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: netmaker-k8s-ops
    app.kubernetes.io/managed-by: kustomize
  name: netmakerops-editor-role
rules:
- apiGroups:
  - network.netmaker.io
  resources:
  - netmakerops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.netmaker.io
  resources:
  - netmakerops/status
  verbs:
  - get
