# permissions for end users to edit netmaker-k8s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: netmaker-k8s-ops
    app.kubernetes.io/managed-by: kustomize
  name: netmaker-k8s-editor-role
rules:
- apiGroups:
  - network.netmaker.io
  resources:
  - netmaker-k8s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.netmaker.io
  resources:
  - netmaker-k8s/status
  verbs:
  - get
