apiVersion: network.netmaker.io/v1
kind: Netmaker-k8s
metadata:
  labels:
    app.kubernetes.io/name: netmaker-k8s-ops
    app.kubernetes.io/managed-by: kustomize
  name: netmaker-k8s-sample
spec:
  # TODO(user): Add fields here
