apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netmaker-k8s-ops.fullname" . }}-env
  namespace: {{ include "netmaker-k8s-ops.namespace" . }}
  labels:
    {{- include "netmaker-k8s-ops.labels" . | nindent 4 }}
data:
  IN_CLUSTER: {{ .Values.manager.configMap.inCluster | default "true" | quote }}
  ENABLE_LEADER_ELECTION: {{ .Values.manager.configMap.enableLeaderElection | default "true" | quote }}
  PROXY_SKIP_TLS_VERIFY: {{ .Values.manager.configMap.proxySkipTLSVerify | default "true" | quote }}
  PROXY_MODE: {{ .Values.manager.configMap.proxyMode | default "auth" | quote }}
  ZAP_LOG_LEVEL: {{ .Values.manager.configMap.verbosity | default "info" | quote }}
  API_SERVER_DOMAIN: {{ .Values.api.serverDomain | default "" | quote }}
  API_TOKEN: {{ .Values.api.token | default "" | quote }}
  API_SYNC_INTERVAL: {{ .Values.api.syncInterval | default "300" | quote }}

