{{- if and .Values.rbac.create .Values.service.metrics.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "netmaker-k8s-ops.fullname" . }}-metrics-auth-rolebinding
  labels:
    {{- include "netmaker-k8s-ops.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "netmaker-k8s-ops.fullname" . }}-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ include "netmaker-k8s-ops.serviceAccountName" . }}
  namespace: {{ include "netmaker-k8s-ops.namespace" . }}
{{- end }}

