{{- if .Values.netclient.token }}
apiVersion: v1
kind: Secret
metadata:
  name: netclient-token
  namespace: {{ include "netmaker-k8s-ops.namespace" . }}
  labels:
    {{- include "netmaker-k8s-ops.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.netclient.token | b64enc | quote }}
{{- end }}
