{{- if and .Values.rbac.create .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "netmaker-k8s-ops.fullname" . }}-leader-election-rolebinding
  namespace: {{ include "netmaker-k8s-ops.namespace" . }}
  labels:
    {{- include "netmaker-k8s-ops.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "netmaker-k8s-ops.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "netmaker-k8s-ops.serviceAccountName" . }}
  namespace: {{ include "netmaker-k8s-ops.namespace" . }}
{{- end }}
