{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netmaker-k8s-ops.fullname" . }}-webhook-service
  namespace: {{ include "netmaker-k8s-ops.namespace" . }}
  labels:
    {{- include "netmaker-k8s-ops.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  ports:
  - port: {{ .Values.service.webhook.port }}
    targetPort: {{ .Values.service.webhook.targetPort }}
    protocol: TCP
    name: webhook
  selector:
    {{- include "netmaker-k8s-ops.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
  type: {{ .Values.service.webhook.type }}
{{- end }}
